cividi/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.core import urls as wagtail_urls
from wagtail.contrib.sitemaps.views import sitemap

from puput import urls as puput_urls
from feedler import urls as feedler_urls

from cividi.search import views as search_views

urlpatterns = [
    url(r'', include(puput_urls)),
    url(r'', include(feedler_urls)),

    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    url('^sitemap\.xml$', sitemap),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.views.generic import TemplateView

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # Add views for testing 404 and 500 templates
    urlpatterns += [
        url(r'^test404/$', TemplateView.as_view(template_name='404.html')),
        url(r'^test500/$', TemplateView.as_view(template_name='500.html')),
    ]


urlpatterns += i18n_patterns(
    # These URLs will have /<language_code>/ appended to the beginning

    url(r'', include(wagtail_urls)),
)

cividi/home/models/forms.py
# -*- coding: utf-8 -*-

from modelcluster.fields import ParentalKey

from django.db.models import CharField

from wagtail.core.fields import RichTextField
from wagtail.contrib.forms.models import (
    AbstractEmailForm, AbstractFormField
)
from wagtail.admin.edit_handlers import (
    FieldPanel, FieldRowPanel,
    InlinePanel, MultiFieldPanel
)

from ..util import TranslatedField

class ContactFormField(AbstractFormField):
    page = ParentalKey('ContactForm', related_name='form_fields')

class ContactForm(AbstractEmailForm):
    intro = RichTextField(default='', blank=True)
    thanks = RichTextField(default='', blank=True)

    content_panels = AbstractEmailForm.content_panels + [
        FieldPanel('intro', classname="full"),
        FieldPanel('thanks', classname="full"),
        InlinePanel('form_fields', label="Form fields"),
        MultiFieldPanel([
            FieldRowPanel([
                FieldPanel('from_address', classname="col6"),
                FieldPanel('to_address', classname="col6"),
            ]),
            FieldPanel('subject'),
        ], "Email"),
    ]

    parent_page_types = ['home.ArticleIndexPage']
    class Meta:
        verbose_name = "Formular"

cividi/home/models/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils import translation
from django.conf import settings

from modelcluster.fields import ParentalKey

from wagtail.core.blocks import StructBlock, CharBlock, URLBlock, RichTextBlock, ListBlock, TextBlock, ChoiceBlock
from wagtail.core.models import Page, Orderable
from wagtail.core.fields import StreamField, RichTextField
from wagtail.admin.edit_handlers import FieldPanel, StreamFieldPanel, InlinePanel, MultiFieldPanel
from wagtail.images.blocks import ImageChooserBlock
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.search import index

from puput.models import EntryPage, BlogPage
from feedler.models import Entry, Stream
from itertools import chain

from ..util import TranslatedField

class InfoBlock(StructBlock):
    title = CharBlock(required=True)
    photo = ImageChooserBlock(required=True)
    summary = RichTextBlock(required=True)
    action = CharBlock(required=False)
    url = URLBlock(required=False)

class ArticleIndexPage(Page):
    title_fr = models.CharField(max_length=255, default="")
    title_en = models.CharField(max_length=255, default="", blank=True)
    trans_title = TranslatedField(
        'title',
        'title_fr',
        'title_en',
    )

    intro_de = RichTextField(default='', blank=True)
    intro_fr = RichTextField(default='', blank=True)
    intro_en = RichTextField(default='', blank=True)
    trans_intro = TranslatedField(
        'intro_de',
        'intro_fr',
        'intro_en',
    )

    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        FieldPanel('intro_de'),
        FieldPanel('title_fr'),
        FieldPanel('intro_fr'),
        FieldPanel('title_en'),
        FieldPanel('intro_en'),
        ImageChooserPanel('feed_image'),
    ]

    def get_context(self, request):
        context = super(ArticleIndexPage, self).get_context(request)
        articles = ArticlePage.objects.child_of(self).live()
        context['articles'] = articles
        subcategories = ArticleIndexPage.objects.child_of(self).live()
        context['subcategories'] = subcategories
        return context

    parent_page_types = [
        'home.ArticleIndexPage',
        'home.HomePage'
    ]
    subpage_types = [
        'home.ArticlePage',
        'home.ArticleIndexPage',
        'home.ContactForm',
        'wagtailcore.Page'
    ]
    class Meta:
        verbose_name = "Rubrik"

class ImageCarouselBlock(StructBlock):
    image = ImageChooserBlock()
    caption = TextBlock(required=False)

    class Meta:
        icon = 'image'

class ArticlePage(Page):
    title_fr = models.CharField(max_length=255, default="")
    title_en = models.CharField(max_length=255, default="", blank=True)
    trans_title = TranslatedField(
        'title',
        'title_fr',
        'title_en',
    )

    intro_de = RichTextField(default='', blank=True)
    intro_fr = RichTextField(default='', blank=True)
    intro_en = RichTextField(default='', blank=True)
    trans_intro = TranslatedField(
        'intro_de',
        'intro_fr',
        'intro_en',
    )

    gallery = StreamField([
        ('image', ListBlock(ImageCarouselBlock(), icon="image")),
    ], blank=True)
    # documents = StreamField([
    #     ('documents', ListBlock(DocumentChooserBlock(), icon="document")),
    # ])

    body_de = StreamField([
        ('paragraph', RichTextBlock()),
        ('section', CharBlock(classname="full title")),
        ('info', InfoBlock(icon='help')),
        ('media', ChoiceBlock(choices=[
            ('gallery', 'Image gallery'),
        ], icon='media'))
    ], null=True, blank=True)
    body_fr = StreamField([
        ('paragraph', RichTextBlock()),
        ('section', CharBlock(classname="full title")),
        ('info', InfoBlock(icon='help')),
        ('media', ChoiceBlock(choices=[
            ('gallery', 'Image gallery'),
        ], icon='media'))
    ], null=True, blank=True)
    body_en = StreamField([
        ('paragraph', RichTextBlock()),
        ('section', CharBlock(classname="full title")),
        ('info', InfoBlock(icon='help')),
        ('media', ChoiceBlock(choices=[
            ('gallery', 'Image gallery'),
        ], icon='media'))
    ], null=True, blank=True)
    trans_body = TranslatedField(
        'body_de',
        'body_fr',
        'body_en',
    )

    date = models.DateField("Date", null=True, blank=True)

    on_homepage = models.BooleanField(default=False, verbose_name="Featured",
        help_text="Auf der Frontpage anzeigen")

    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    search_fields = Page.search_fields + [
        index.SearchField('title',    partial_match=True, boost=10),
        index.SearchField('title_fr', partial_match=True, boost=10),
        index.SearchField('title_en', partial_match=True, boost=10),
        index.SearchField('body_de',  partial_match=True),
        index.SearchField('body_fr',  partial_match=True),
        index.SearchField('body_en',  partial_match=True),
        index.SearchField('intro_de', partial_match=True),
        index.SearchField('intro_fr', partial_match=True),
        index.SearchField('intro_en', partial_match=True),
    ]
    content_panels = [
        MultiFieldPanel([
            FieldPanel('title'),
            FieldPanel('intro_de'),
        ], heading="Deutsch",
           classname="collapsible collapsed"),
        StreamFieldPanel('body_de'),
        MultiFieldPanel([
            FieldPanel('title_fr'),
            FieldPanel('intro_fr'),
        ], heading="Français",
           classname="collapsible collapsed"),
        StreamFieldPanel('body_fr'),
        MultiFieldPanel([
            FieldPanel('title_en'),
            FieldPanel('intro_en'),
        ], heading="English",
           classname="collapsible collapsed"),
        StreamFieldPanel('body_en'),
        MultiFieldPanel([
            ImageChooserPanel('feed_image'),
        ], heading="Images"),
        StreamFieldPanel('gallery'),
    ]
    promote_panels = [
        InlinePanel('related_links', label="Links"),
        MultiFieldPanel([
            FieldPanel('date'),
            FieldPanel('on_homepage'),
        ], heading="Veröffentlichung"),
        MultiFieldPanel(Page.promote_panels, "Einstellungen"),
    ]

    parent_page_types = [
        'home.ArticleIndexPage',
        'home.HomePage'
    ]
    subpage_types = []
    class Meta:
        verbose_name = "Artikel"

class ArticleRelatedLink(Orderable):
    page = ParentalKey(ArticlePage, related_name='related_links')
    name = models.CharField(max_length=255)
    url = models.URLField()
    panels = [
        FieldPanel('name'),
        FieldPanel('url'),
    ]

class HomePage(Page):
    intro_de = RichTextField(default='')
    intro_fr = RichTextField(default='')
    intro_en = RichTextField(default='', blank=True)
    trans_intro = TranslatedField(
        'intro_de',
        'intro_fr',
        'intro_en',
    )

    body_de = RichTextField(default='', blank=True)
    body_fr = RichTextField(default='', blank=True)
    body_en = RichTextField(default='', blank=True)
    trans_body = TranslatedField(
        'body_de',
        'body_fr',
        'body_en',
    )

    infos_de = StreamField([
        ('info', InfoBlock())
    ], null=True, blank=True)
    infos_fr = StreamField([
        ('info', InfoBlock())
    ], null=True, blank=True)
    infos_en = StreamField([
        ('info', InfoBlock())
    ], null=True, blank=True)
    trans_infos = TranslatedField(
        'infos_de',
        'infos_fr',
        'infos_en',
    )

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('intro_de', classname="full"),
            FieldPanel('body_de', classname="full"),
            StreamFieldPanel('infos_de'),
        ], heading="Deutsch",
           classname="collapsible collapsed"),
        MultiFieldPanel([
            FieldPanel('intro_fr', classname="full"),
            FieldPanel('body_fr', classname="full"),
            StreamFieldPanel('infos_fr'),
        ], heading="Français",
           classname="collapsible collapsed"),
        MultiFieldPanel([
            FieldPanel('intro_en', classname="full"),
            FieldPanel('body_en', classname="full"),
            StreamFieldPanel('infos_en'),
        ], heading="English",
           classname="collapsible collapsed"),
    ]

    @property
    def featured(self):
        # Get list of live pages that are descendants of this page
        articles = ArticlePage.objects.live().descendant_of(self)
        articles = articles.filter(on_homepage=True)
        articles = articles.filter(feed_image__isnull=False)
        # Order by most recent date first
        #articles = articles.order_by('-date')
        return articles[:4]

    @property
    def blogentries(self):
        # Get list of latest news
        curlang = translation.get_language()
        if not curlang in ['de', 'fr', 'en', 'it']: curlang = 'de' # Default language
        parent = BlogPage.objects.filter(slug='news-%s' % curlang)
        if not parent: return []
        posts = EntryPage.objects.live().descendant_of(parent[0])
        # Order by most recent date first
        posts = posts.order_by('-date')
        return posts[:settings.BLOG_ENTRIES_HOME_PAGE]

    @property
    def newsentries(self):
        # Get the last few news entries for the home page
        entries = Entry.objects.all().order_by('-published')
        # Filter out by current language
        curlang = translation.get_language()
        if curlang in ['de']:
            entries = entries.exclude(lang='fr')
        else:
            entries = entries.exclude(lang='de')

cividi/home/models/snippets.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

from wagtail.snippets.models import register_snippet

from wagtail.core.models import Page
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.admin.edit_handlers import FieldPanel, PageChooserPanel

from .forms import ContactForm
from ..util import TranslatedField

# List of supported social networks
SOCIAL_NETWORK_SUPPORTED = (
    ('twitter', 'Twitter'),
    ('facebook', 'Facebook'),
)

@register_snippet
class SocialContact(models.Model):
    """
    Adds contact options through social networks
    """
    network = models.CharField(max_length=16, default="twitter",
        choices=SOCIAL_NETWORK_SUPPORTED)
    profile = models.CharField(max_length=255, default="",
        help_text="Name of the account, e.g. @myaccount, or full URL")
    home_site = models.ForeignKey(
        'wagtailcore.Site', null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='+')
    panels = [
        FieldPanel('network'),
        FieldPanel('profile'),
        FieldPanel('home_site'),
    ]
    social_networks = dict(SOCIAL_NETWORK_SUPPORTED)
    def network_title(self):
        return self.social_networks[self.network]
    def network_url(self):
        if '://' in self.profile:
            return self.profile
        if self.network == 'twitter':
            return "https://twitter.com/%s" % self.profile
        elif self.network == 'facebook':
            return "https://facebook.com/%s" % self.profile
        return "#"
    def __str__(self):
        return "%s" % self.network

@register_snippet
class Contact(models.Model):
    """
    Defines contact options for the organisation, usually shown in footer
    """
    title = models.CharField(max_length=255, default="")
    title_fr = models.CharField(max_length=255, default="")
    title_en = models.CharField(max_length=255, default="")
    trans_title = TranslatedField(
        'title',
        'title_fr',
        'title_en',
    )

    address = models.TextField(default="", blank=True)
    phone = models.CharField(max_length=40, blank=True, default="")
    email = models.EmailField(max_length=100, blank=True, default="")
    www = models.URLField(null=True, blank=True)

    style = models.TextField(default="", blank=True)
    color = models.CharField(max_length=40, blank=True, default="")
    logo = models.ForeignKey(
        'wagtailimages.Image',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    map_url = models.URLField(null=True, blank=True,
        help_text="Optional link of address to mapping provider")
    analytics = models.CharField(max_length=60, default="", blank=True,
        help_text="Optional web analytics property code")

    contact_form = models.ForeignKey(
        'home.ContactForm',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    home_site = models.ForeignKey(
        'wagtailcore.Site',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    panels = Page.content_panels + [
        FieldPanel('title_fr'),
        FieldPanel('title_en'),
        FieldPanel('home_site'),
        FieldPanel('address'),
        FieldPanel('phone'),
        FieldPanel('email'),
        FieldPanel('www'),
        ImageChooserPanel('logo'),
        FieldPanel('color'),
        FieldPanel('style'),
        FieldPanel('map_url'),
        FieldPanel('analytics'),
        PageChooserPanel('contact_form', 'home.ContactForm'),
    ]

    def phone_link(self):
        return 'tel:%s' % self.phone.replace(' ', '')
    def email_link(self):
        return 'mailto:%s' % self.email
    def www_domain(self):
        return self.www.replace('http://', '').replace('https://', '')
    def is_google_analytics(self):
        return self.analytics.startswith('UA-')
    def get_piwik_analytics(self):
        # When formatted as "server|site_id", assume Piwik
        if not '|' in self.analytics: return False
        sa = self.analytics.split('|')
        return { 'server': sa[0], 'site': sa[1] }
    def trans_title_styled(self):
        v = self.trans_title.split(' ')
        if len(v) != 3: return self.trans_title
        return "<strong>%s %s</strong> %s" % tuple(v)
    def __str__(self):
        return self.trans_title

cividi/home/routes.py
# -*- coding: utf-8 -*-

from datetime import date

from django.utils.dateformat import DateFormat
from django.utils.formats import date_format
from django.utils.translation import ugettext_lazy as _

from wagtail.core.models import Page
from wagtail.search.models import Query
from wagtail.contrib.routable_page.models import RoutablePageMixin, route

class HomePage(RoutablePageMixin, Page):

    @route(r'^$')
    def home_page(self, request, *args, **kwargs):
        self.articles = self.get_articles()
        return Page.serve(self, request, *args, **kwargs)

cividi/home/templates/tags/contact_info.html
{% load wagtailimages_tags %}

<address>
  <p>
  {% if contact.map_url %}
    <a href="{{ contact.map_url }}">{{ contact.address|linebreaks }}</a>
  {% else %}
    {{ contact.address|linebreaks }}
  {% endif %}
  </p>
  <p><small>Tel.</small> <a href="{{ contact.phone_link }}">{{ contact.phone }}</a><br>
  <a href="{{ contact.email_link }}">{{ contact.email }}</a><br>
  <a href="{{ contact.www }}">{{ contact.www_domain }}</a></p>
</address>

<div class="social-networks">
{% for sc in socials %}
  <a href="{{ sc.network_url }}" target="_blank" title="{{ sc.network_title }}"
     style="background-image:url(/static/images/social/{{ sc.network }}.png)">
     {{ sc.network_title }}</a>
{% endfor %}
</div>

<style type="text/css">
{{ contact.style }}
{% if contact.color %}
  footer#footer, .navbar-pre {
     background-color: {{ contact.color }};
  }
{% endif %}
{% if contact.logo %}
  {% image contact.logo original as contact_logo %}
  .navbar-brand {
    background-size: contain !important;
    background-repeat: no-repeat;
    background-image: url('{{ contact_logo.url }}');
    padding-left: 80px;
  }
  .navbar-brand img { display: none !important; }
{% endif %}
</style>

{% if contact.is_google_analytics %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ contact.analytics }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '{{ contact.analytics }}');
</script>

{% elif contact.get_piwik_analytics %}
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
  _paq.push(["setCookieDomain", document.domain]);
  _paq.push(["setDomains", [document.domain,"*." + document.domain]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//{{ contact.get_piwik_analytics.server }}";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', {{ contact.get_piwik_analytics.site }}]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
{% endif %}

cividi/home/templates/tags/contact_links.html
<span class="social-networks">
{% for sc in socials %}
  <a href="{{ sc.network_url }}" target="_blank" title="{{ sc.network_title }}"
     style="background-image:url(/static/images/social/{{ sc.network }}.png)">
     <span class="hidden">{{ sc.network_title }}</span></a>
{% endfor %}
</span>

<a href="{{ contact.phone_link }}" class="hidden">
  <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
  <span class="hidden">{{ contact.phone }}</span></a>

<a href="{{ contact.email_link }}" class="hidden">
  <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
  <span class="hidden">{{ contact.email }}</span></a>

cividi/home/templates/tags/contact_name.html
{% if html %}{{ contact.trans_title_styled|safe }}{% else %}{{ contact.title }}{% endif %}

cividi/home/templates/tags/footer_form.html
{% load wagtailcore_tags %}
{% if form %}
<form action="{% pageurl form %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <input name="name" id="id_name" type="text" placeholder="Name / Nom" class="form-control" required>
  </div>
  <div class="form-group">
    <input name="email" id="id_email" type="email" placeholder="E-Mail" class="form-control" required>
  </div>
  <div class="form-group">
    <textarea name="message" id="id_message" rows="3" placeholder="Nachricht / Message" class="form-control" required></textarea>
  </div>
  <button class="btn btn-primary" type="submit">Senden / Envoi</button>
</form>
{% endif %}

cividi/home/templates/tags/footer_menu.html
{% load navigation wagtailcore_tags %}

<ul class="list-unstyled">
  {% for menuitem in menuitems %}
    <li><a href="{% pageurl menuitem %}">{{ menuitem.title }}</a></li>
  {% endfor %}
</ul>

cividi/home/templates/tags/language.html
{% for lang in languages %}
  <a lang="{{ lang.code }}" {% if lang.code == currentlangcode %}class="active"{% endif %} href="{{ lang.url }}">{{ lang.title }}</a>
{% endfor %}

cividi/home/templates/tags/top_menu.html
{% load navigation wagtailcore_tags %}

<ul class="navbar-nav mr-auto">
  {% for menuitem in menuitems %}
    {% if menuitem.show_dropdown %}
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {{ menuitem.title }}
      </a>
      <div class="dropdown-menu">
        {% top_menu_children parent=menuitem %}
      </div>
    </div>
    {% else %}
    <li class="nav-item{% if menuitem.active %} active{% endif %}">
      <a class="nav-link" href="{% pageurl menuitem %}">{{ menuitem.title }}</a>
    </li>
    {% endif %}
  {% endfor %}
</ul>
<!-- /.navbar-collapse -->

cividi/home/templates/tags/top_menu_children.html
{% load navigation wagtailcore_tags %}

{% for child in menuitems_children %}
    <a class="dropdown-item" href="{% pageurl child %}">{{ child.title }}</a>
{% endfor %}
</ul>